# Generated by Django 3.0.3 on 2021-03-16 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('target', models.TextField()),
                ('hit_count', models.IntegerField(default=0)),
            ],
        ),
    ]
