# CircleCI Jobs
jobs:
  test_app:
    docker:
      - image: circleci/python:3.8.1-buster
        environment:
          DATABASE_HOST: "localhost"
          DATABASE_NAME: pangea
          DATABASE_USER: postgres
          DATABASE_PASSWORD: ""
      - image: circleci/postgres:11.6
        environment:
          POSTGRES_DB: pangea
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ""

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install Python Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Provision database
          command: |
            . venv/bin/activate
            python manage.py migrate

      - run:
          name: Run application tests
          command: |
            . venv/bin/activate
            python manage.py test

      # - store_artifacts:
      #     path: htmlcov
      #     destination: test-reports

workflows:
  version: 2

  app_cd:
    jobs:
      - test_app
