
ALLOWED_NAME_TYPES = [
    'acronym',
    'anamorph',
    'authority',
    'blast name',
    'common name',
    'equivalent name',
    'genbank acronym',
    'genbank anamorph',
    'genbank common name',
    'genbank synonym',
    'in-part',
    'includes',
    'scientific name',
    'synonym',
    'teleomorph',
    'type material',
]

MD2_COLUMN_NAMES = [
    'human_commensal',
    'antimicrobial_susceptibility',
    'optimal_temperature',
    'extreme_environment',
    'optimal_ph',
    'animal_pathogen',
    'spore_forming',
    'pathogenicity',
    'plant_pathogen',
    'salinity_concentration_range_w_v',
    'biofilm_forming',
    'halotolerance',
    'low_ph',
    'high_ph',
    'drylands',
    'low_productivity',
    'gram_stain',
    'psychrophilic',
    'radiophilic',
    'virus_name',
    'virus_lineage',
    'kegg_genome',
    'kegg_disease',
    'disease',
    'host_name',
    'host_lineage',
]