# Generated by Django 3.0.3 on 2020-03-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='core_sample_group_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pangeauser',
            name='personal_org_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
