# Generated by Django 3.0.3 on 2020-03-29 04:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200323_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='S3ApiKey',
            fields=[
                ('created_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(default='')),
                ('endpoint_url', models.TextField()),
                ('bucket', models.TextField(default='*')),
                ('public_key', models.TextField()),
                ('private_key', models.TextField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s3_api_keys', to='core.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
