# Generated by Django 3.0.3 on 2020-02-05 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200205_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='sample_groups',
            field=models.ManyToManyField(to='core.SampleGroup'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_samples', to='core.SampleGroup'),
        ),
    ]
