# Generated by Django 3.0.3 on 2020-02-05 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200205_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleanalysisresult',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_result_set', to='core.Sample'),
        ),
        migrations.AlterField(
            model_name='sampleanalysisresultfield',
            name='analysis_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='core.SampleAnalysisResult'),
        ),
        migrations.AlterField(
            model_name='samplegroupanalysisresult',
            name='sample_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_result_set', to='core.SampleGroup'),
        ),
        migrations.AlterField(
            model_name='samplegroupanalysisresultfield',
            name='analysis_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='core.SampleGroupAnalysisResult'),
        ),
    ]
