# Generated by Django 3.0.3 on 2020-03-29 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_samplegroup_is_library'),
        ('core', '0003_s3apikey'),
    ]

    operations = [
    ]
