# Generated by Django 3.0.3 on 2020-08-22 01:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_merge_20200329_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='s3apikey',
            name='endpoint_url',
        ),
        migrations.RemoveField(
            model_name='s3apikey',
            name='organization',
        ),
        migrations.AddField(
            model_name='pangeauser',
            name='saved_sample_groups',
            field=models.ManyToManyField(to='core.SampleGroup'),
        ),
        migrations.CreateModel(
            name='S3Bucket',
            fields=[
                ('created_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('endpoint_url', models.TextField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='samplegroup',
            name='bucket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.S3Bucket'),
        ),
        migrations.AlterField(
            model_name='s3apikey',
            name='bucket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='core.S3Bucket'),
        ),
    ]
