# Generated by Django 3.0.3 on 2020-09-05 22:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import pangea.core.encrypted_fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200822_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleanalysisresult',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='samplegroupanalysisresult',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('description', models.TextField(default='')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization')),
                ('sample_groups', models.ManyToManyField(null=True, to='core.SampleGroup')),
                ('sub_projects', models.ManyToManyField(null=True, related_name='super_projects', to='core.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
