# Generated by Django 3.0.3 on 2020-09-07 21:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import pangea.core.encrypted_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200905_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='sample_groups',
            field=models.ManyToManyField(blank=True, null=True, to='core.SampleGroup'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sub_projects',
            field=models.ManyToManyField(blank=True, null=True, related_name='super_projects', to='core.Project'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sample',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='sampleanalysisresult',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sampleanalysisresult',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='samplegroup',
            name='long_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='samplegroup',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='samplegroupanalysisresult',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='samplegroupanalysisresult',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
