# Generated by Django 3.0.3 on 2020-12-15 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pangea.core.encrypted_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200907_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplegroup',
            name='guest_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
