# Generated by Django 3.0.3 on 2020-12-28 16:49

from django.db import migrations, models
import django.db.models.deletion
import pangea.core.encrypted_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201215_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleanalysisresult',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='samplegroupanalysisresult',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
