# Generated by Django 3.0.3 on 2021-01-22 15:23

from django.db import migrations


def forwards(apps, schema_editor):
    SampleModel = apps.get_model('core', 'Sample')
    VMModel = apps.get_model('core', 'VersionedMetadata')
    VMModel.objects.bulk_create(
        VMModel(metadata=sample.metadata, sample=sample)
        for sample in SampleModel.objects.all()
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210122_1522'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
