# Generated by Django 3.0.3 on 2021-01-22 15:47

from django.db import migrations, models
import django.db.models.deletion
import pangea.core.encrypted_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210122_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='metadata',
        ),
        migrations.AddField(
            model_name='versionedmetadata',
            name='sample',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versioned_metadata', to='core.Sample'),
        ),
    ]
