# Generated by Django 3.0.3 on 2021-01-22 15:47

from django.db import migrations, models
import django.db.models.deletion
import pangea.core.encrypted_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210122_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='metadata',
        ),
    ]
