# Generated by Django 3.0.3 on 2021-02-05 00:25

from django.db import migrations, models
import django.db.models.deletion
import pangea.core.encrypted_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210204_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinemodule',
            name='dependencies',
            field=models.ManyToManyField(blank=True, null=True, related_name='downstreams', to='core.PipelineModule'),
        ),
        migrations.AddField(
            model_name='sampleanalysisresult',
            name='pipeline_module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sample_analysis_results', to='core.PipelineModule'),
        ),
        migrations.AddField(
            model_name='samplegroupanalysisresult',
            name='pipeline_module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sample_group_analysis_results', to='core.PipelineModule'),
        ),
    ]
