# Generated by Django 3.0.3 on 2021-02-26 16:53

from django.db import migrations, models
import django.db.models.deletion
import pangea.core.encrypted_fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210205_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='pangeauser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='pangeauser',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pangeauser',
            name='company',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pangeauser',
            name='github_username',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pangeauser',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pangeauser',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pangeauser',
            name='twitter_username',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pangeauser',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pangeauser',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
