# Generated by Django 3.0.3 on 2021-02-26 17:22

from django.db import migrations, models
import django.db.models.deletion
import pangea.core.encrypted_fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210226_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pangeauser',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
