# Generated by Django 3.0.3 on 2021-02-26 17:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_populate_pangea_user_uuid_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pangeauser',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
