# Generated by Django 3.0.3 on 2021-03-01 22:36

from django.db import migrations, models
import django.db.models.deletion
import pangea.core.encrypted_fields
import pangea.core.custom_fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_null_pangea_user_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='S3Provider',
            fields=[
                ('created_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('s3_endpoint_url', models.TextField()),
                ('iam_endpoint_url', models.TextField()),
                ('public_key', models.TextField(default=None)),
                ('private_key', models.TextField(default=None)),
                ('default_provider', pangea.core.custom_fields.AtMostOneBooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='s3bucket',
            name='storage_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buckets', to='core.S3Provider'),
        ),
        migrations.AddField(
            model_name='samplegroup',
            name='storage_provider_name',
            field=models.TextField(default='custom'),
        ),
    ]
