# Generated by Django 3.0.3 on 2021-03-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20210311_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborder',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='joborderproto',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='workorder',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='workorderproto',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
