# Generated by Django 3.0.3 on 2021-04-16 15:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import pangea.core.encrypted_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20210312_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplegroup',
            name='sample_metadata_schema',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
