# Generated by Django 3.0.3 on 2021-04-22 14:30

from django.db import migrations, models
import django.db.models.deletion
import pangea.core.encrypted_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20210416_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleanalysisresult',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sampleanalysisresultfield',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='samplegroupanalysisresult',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='samplegroupanalysisresultfield',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
