# Generated by Django 3.0.3 on 2021-04-24 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20210422_1430'),
        ('core', '0022_auto_20210423_1949'),
    ]

    operations = [
    ]
