# Generated by Django 3.0.3 on 2021-05-11 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pangea.core.encrypted_fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20210426_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wiki',
            fields=[
                ('created_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WikiPage',
            fields=[
                ('created_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(unique=True)),
                ('text', models.TextField(blank=True, default='')),
                ('wiki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='core.Wiki')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='wiki',
            name='home_page',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_wiki', to='core.WikiPage'),
        ),
        migrations.AddField(
            model_name='wiki',
            name='sidebar',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sidebar_wiki', to='core.WikiPage'),
        ),
        migrations.CreateModel(
            name='SiteWiki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('wiki', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Wiki')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.TextField(choices=[('full site', 'full site')], default='full site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SampleGroupWiki',
            fields=[
                ('created_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sample_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='wiki', serialize=False, to='core.SampleGroup')),
                ('wiki', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Wiki')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
