# Generated by Django 3.0.3 on 2021-06-20 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metasub', '0003_auto_20210617_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='koboasset',
            name='kobo_id',
            field=models.TextField(editable=False, unique=True),
        ),
    ]
